apiVersion: v1
kind: Service
metadata:
  namespace: {{namespace}}
  name: {{applicationName}}
  labels:
    name: {{applicationName}}
    role: server
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
      targetPort: 8080
  selector:
    name: {{applicationName}}