apiVersion: system.codezero.io/v1
kind: App
metadata:
  name: echo-server
  labels:
    system.codezero.io/edition: latest
  annotations:
    system.codezero.io/display: Echo Server
    system.codezero.io/description: "A dumb echo service"
    system.codezero.io/iconUrl: "https://hub.codezero.io/api/assets/apps/01E8Q6AARJG3Q6XWEVDD7FYZ9V/icon"
spec:
  routes:
    - type: http
      targetService: echo-server
  provisioner:
    package: "@provisioner/echo-server-provisioner"
    ui: ignore
  marina:
    launch:
      type: inline